# Generated by Django 2.1.5 on 2020-02-04 14:04

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='post',
            name='steps',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), size=100),
        ),
        migrations.AddField(
            model_name='post',
            name='used_ingredients',
            field=models.ManyToManyField(to='recipe.Ingredients'),
        ),
    ]
