# Generated by Django 2.1.5 on 2020-02-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200204_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='steps',
            field=models.TextField(),
        ),
    ]
